export { project } from './data/project.js'
export { techGroups, techTopics } from './data/tech.js'
export { aiTopics, aiTemplates } from './data/collaboration.js'
export { conceptTopics } from './data/concepts.js'
export { automationLevels, workflowRecipes } from './data/automation.js'
export { practicalGuides, fieldTips } from './data/practical.js'
export { toolPurposes, aiTools, toolRecipes } from './data/tools.js'
export { projectRecipes } from './data/projects.js'
